In [1]:
# make sure to use the right version of pytorch when testing on nvidia/amd
import torch
# import torch.nn.functional as F
torch.set_printoptions(sci_mode=False)
from torch.nn.functional import scaled_dot_product_attention

In [2]:
import math
M = 32


def flashattn(Q: torch.Tensor, K: torch.Tensor, V: torch.Tensor) -> torch.Tensor:
    assert Q.shape == K.shape == V.shape
    assert len(Q.shape) == 2

    K = K.T

    # seq length, inner dim of representations
    N, d = Q.shape

    # of kv vectors per tile
    bc = math.ceil(M/(4*d))
    tc = math.ceil(N/bc)
    K_shared = torch.empty((d, bc), dtype=Q.dtype)
    V_shared = torch.empty((bc, d), dtype=Q.dtype)

    # of q vectors per tile
    br = min(math.ceil(M/(4*d)), d)
    tr = math.ceil(N/br)
    Q_shared = torch.empty((br, d), dtype=Q.dtype)

    # print(f'bc={bc}, br={br}')
    # print(f'tc={tc}, tr={tr}')

    # output matrix
    O = torch.zeros_like(Q)
    O_shared = torch.empty_like(Q_shared)

    # intermediate rowmaxes
    m = torch.full((N,), -torch.inf, dtype=Q.dtype)
    m_shared = torch.empty((br, 1), dtype=Q.dtype)
    # intermediate normalization constants
    l = torch.full((N,), 0, dtype=Q.dtype)
    l_shared = torch.empty((br, 1), dtype=Q.dtype)

    for i in range(tc):
        # load k, v chunks
        # make sure we load in k as its transposed version
        K_shared[:, :] = K[:, i*bc:(i+1)*bc]
        V_shared[:, :] = V[i*bc:(i+1)*bc, :]

        for j in range(tr):
            # load in q, o, m, l
            Q_shared[:, :] = Q[j*br:(j+1)*br, :]
            # if i == 0: print(f'Q: {Q_shared}')
            O_shared[:, :] = O[j*br:(j+1)*br, :]
            m_shared[:, :] = m[j*br:(j+1)*br].unsqueeze(-1)
            l_shared[:, :] = l[j*br:(j+1)*br].unsqueeze(-1)
            
            S = Q_shared @ K_shared

            # get row-wise softmax statistics
            mt = S.max(dim=1).values.reshape(-1, 1)

            Pt = torch.exp(S - mt)
            lt = Pt.sum(dim=1).reshape(-1, 1)

            # compute new statistics
            m_new = torch.max(mt, m_shared)
            l_new = (torch.exp(m_shared - m_new) * l_shared) + (torch.exp(mt - m_new) * lt)


            # update chunk of output
            O_new = (l_shared * torch.exp(m_shared - m_new) * O_shared + torch.exp(mt - m_new) * Pt @ V_shared) / l_new
            O[j*br:(j+1)*br, :] = O_new
            
            m[j*br:(j+1)*br] = m_new.flatten()
            l[j*br:(j+1)*br] = l_new.flatten()

    return O






In [50]:
from math import sqrt

def dumb_attn(Q: torch.Tensor, K: torch.Tensor, V: torch.Tensor) -> torch.Tensor:
    """equivalent to F.scaled_dot_product_attention(Q, K, V, scale=1)"""
    d = Q.shape[1]
    return torch.softmax((Q)@ K.T, dim=1) @ V
    # return F.scaled_dot_product_attention(Q, K, V, scale=1)


# have to support up to like d=128
# Model dim of 4096 is divided ACROSS HEADS
# we're giving up and only supporting fp16 (like flashattn)
# Q = torch.rand((8196, 128), dtype=torch.float16, device='cuda') 
# K = torch.rand((8196, 128), dtype=torch.float16, device='cuda') 
# V = torch.rand((8196, 128), dtype=torch.float16, device='cuda') 

# K[-1] = torch.zeros((2,))
# V[-1] = torch.zeros((2,))


Q = torch.randint(1, 9, (32, 16), device='cuda').to(torch.float16)
K = torch.randint(1, 9, (32, 16), device='cuda').to(torch.float16)
V = torch.randint(1, 9, (32, 16), device='cuda').to(torch.float16)


# Q = torch.tensor([[0., 1.],
#          [2., 3.]])

# K = torch.tensor([[0., 1.5],
#          [2., 3.]])

# V = torch.tensor([[1., 0.],
#          [0., 1.]])
Q, K, V


(tensor([[8., 2., 6., 1., 7., 6., 4., 4., 3., 5., 7., 5., 4., 7., 5., 4.],
         [4., 2., 1., 1., 3., 7., 6., 8., 2., 4., 4., 8., 4., 8., 2., 8.],
         [3., 3., 5., 8., 3., 5., 5., 4., 6., 4., 2., 3., 5., 3., 5., 3.],
         [2., 6., 8., 1., 1., 5., 6., 3., 8., 4., 8., 4., 4., 6., 4., 5.],
         [7., 2., 7., 8., 6., 3., 1., 7., 1., 6., 8., 2., 6., 6., 1., 2.],
         [8., 8., 1., 1., 5., 8., 7., 7., 6., 6., 8., 6., 8., 7., 6., 4.],
         [5., 3., 8., 3., 8., 7., 4., 3., 1., 3., 1., 3., 8., 3., 1., 3.],
         [8., 5., 7., 5., 2., 4., 2., 4., 2., 2., 8., 2., 3., 1., 8., 6.],
         [5., 3., 5., 1., 2., 5., 3., 4., 2., 7., 2., 2., 3., 7., 5., 3.],
         [3., 5., 2., 7., 8., 1., 4., 7., 2., 3., 6., 5., 8., 2., 3., 2.],
         [6., 5., 8., 1., 4., 4., 6., 5., 2., 3., 4., 2., 3., 8., 7., 6.],
         [6., 2., 5., 2., 8., 1., 3., 4., 2., 2., 1., 7., 1., 3., 6., 7.],
         [6., 7., 3., 6., 1., 8., 4., 1., 4., 8., 7., 4., 1., 2., 7., 2.],
         [8., 3., 1., 3.,

In [3]:
from torch.utils.cpp_extension import load
module = load(
    name='m',
    sources=['rocm/flash_attention.hip',],
    extra_cflags=['--offload-arch="gfx1100"'],
    build_directory='build',
    verbose=True
)

/home/seb/Code/flash-attention/rocm/flash_attention.hip -> /home/seb/Code/flash-attention/rocm/flash_attention_hip.hip [ok]
Total number of unsupported CUDA function calls: 0


Total number of replaced kernel launches: 3


The input conditions for extension module m have changed. Bumping to version 2 and re-building as m_v2...
Successfully preprocessed all matching files.
Detected CUDA files, patching ldflags
Emitting ninja build file build/build.ninja...
Building extension module m_v2...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


[1/2] /opt/rocm-6.1.3/bin/hipcc  -DWITH_HIP -DTORCH_EXTENSION_NAME=m_v2 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/seb/Code/pyenvs/rocmenv/lib/python3.12/site-packages/torch/include -isystem /home/seb/Code/pyenvs/rocmenv/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /home/seb/Code/pyenvs/rocmenv/lib/python3.12/site-packages/torch/include/TH -isystem /home/seb/Code/pyenvs/rocmenv/lib/python3.12/site-packages/torch/include/THC -isystem /home/seb/Code/pyenvs/rocmenv/lib/python3.12/site-packages/torch/include/THH -isystem /opt/rocm-6.1.3/include -isystem /home/seb/miniconda3/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 --offload-arch="gfx1100" -fPIC -D__HIP_PLATFORM_AMD__=1 -DUSE_ROCM=1 -DHIPBLAS_V2 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -fno-gpu-rdc -c /home/seb/Code/flash-attention/rocm/flash_at

Loading extension module m_v2...


In [ ]:
# torch.isclose(dumb_attn(Q, K, V), flashattn(Q, K, V))
# dumb_attn(Q, K, V), flashattn(Q, K, V)

# F.scaled_dot_product_attention(Q, K, V, scale=1), flashattn(Q, K, V)
# module.flash_attn(Q, K, V)
torch.set_printoptions(profile='default', sci_mode=False)
r1 = dumb_attn(Q, K, V)
r2 = module.flash_attn(Q, K, V)
(r1-r2).abs().mean()
# r1, r2
# Q @ K.T


# # r1, dumb_attn(Q.float(), K.float(), V.float()), r2
# # r1, r2[:50]
# dumb_attn(Q, K, V), module.flash_attn(Q, K, V)

In [56]:

def test_flashattn():
    diff = lambda r1, r2: (r1-r2).abs().mean()
    # dims = ((67, 128), (48, 128))
    dims = ((48, 32), (64, 128), (1024, 128), (4096, 128))
    for N, d in dims:
        Q = torch.rand((N, d), dtype=torch.float16, device='cuda') 
        K = torch.rand((N, d), dtype=torch.float16, device='cuda') 
        V = torch.rand((N, d), dtype=torch.float16, device='cuda') 

        # print(f'Difference on ({N}, {d}) tensors: {diff(dumb_attn(Q, K, V), F.scaled_dot_product_attention(Q, K, V, scale=1))}\n\n')
        res = module.flash_attn(Q, K, V)
        # print(torch.isnan(res).any())
        # print(res, res.shape)
        print(f'Difference on ({N}, {d}) tensors: {diff(res, F.scaled_dot_product_attention(Q, K, V, scale=1))}\n\n')

        # print(f'Difference on ({N}, {d}) tensors: {diff(module.flash_attn(Q, K, V), dumb_attn(Q, K, V))}\n\n')

torch.set_printoptions(profile='full', sci_mode=False)
test_flashattn()
torch.set_printoptions(profile='default', sci_mode=False)

tc=1, tr=2
Launching kernel with smem size 13312
Difference on (48, 32) tensors: 0.00016057491302490234


tc=2, tr=2
Launching kernel with smem size 44032
Difference on (64, 128) tensors: 0.000621795654296875


tc=22, tr=32
Launching kernel with smem size 44032
Difference on (1024, 128) tensors: 0.0006356239318847656


tc=86, tr=128
Launching kernel with smem size 44032
Difference on (4096, 128) tensors: 0.0010166168212890625




In [41]:
# A = torch.rand((16, 32), dtype=torch.float16, device='cuda')
# B = torch.rand((32, 16), dtype=torch.float16, device='cuda')

A = torch.randint(0, 2, (16, 16), dtype=torch.float16, device='cuda')
B = torch.randint(0, 2, (16, 32), dtype=torch.float16, device='cuda')

# A = torch.eye(16, dtype=torch.float16, device='cuda') 
# B = torch.eye(16, dtype=torch.float16, device='cuda')

# A = torch.ones((16, 16), dtype=torch.float16, device='cuda') 
# B = torch.zeros((16, 16), dtype=torch.float16, device='cuda') 

A, B

(tensor([[1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1.],
         [0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0.],
         [0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0.],
         [1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1.],
         [0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1.],
         [1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0.],
         [1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0.],
         [0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.],
         [0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.],
         [0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
         [1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.],
         [1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0.],
         [1., 1., 0., 0.,

In [48]:
# print(module.matmul(A, B), (A @ B))
torch.set_printoptions(profile='full', sci_mode=False)
print(torch.allclose(module.matmul(A, B, False), A @ B))
module.matmul(A, B, False) - A @ B

Warp 0 computing tile 0 of matrix, coords (0, 0), will do 1 loops
Warp 0 loading from idx 0 of a and idx 0 of b
Warp 0 computing tile 1 of matrix, coords (0, 1), will do 1 loops
Warp 0 loading from idx 0 of a and idx 16 of b
True
Warp 0 computing tile 0 of matrix, coords (0, 0), will do 1 loops
Warp 0 loading from idx 0 of a and idx 0 of b
Warp 0 computing tile 1 of matrix, coords (0, 1), will do 1 loops
Warp 0 loading from idx 0 of a and idx 16 of b


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 

In [45]:
Qp = F.pad(Q, (0, 16-4, 0, 32-5))
Kp = F.pad(K, (0, 16-4, 0, 48-5))

# Qp, Kp
print(Qp.shape, Kp.T.shape)
(module.matmul(Qp, Kp.T.contiguous(), False), (Qp @ Kp.T))
# torch.allclose(module.matmul(Qp, Kp.T, False), module.matmul(Qp, Kp, True))

torch.Size([32, 16]) torch.Size([16, 48])
Warp 0 computing tile 0 of matrix, coords (0, 0), will do 1 loops
Warp 0 loading from idx 0 of a and idx 0 of b
Warp 0 computing tile 1 of matrix, coords (0, 1), will do 1 loops
Warp 0 loading from idx 0 of a and idx 16 of b
Warp 0 computing tile 2 of matrix, coords (0, 2), will do 1 loops
Warp 0 loading from idx 0 of a and idx 32 of b
Warp 0 computing tile 3 of matrix, coords (1, 0), will do 1 loops
Warp 0 loading from idx 256 of a and idx 0 of b
Warp 0 computing tile 4 of matrix, coords (1, 1), will do 1 loops
Warp 0 loading from idx 256 of a and idx 16 of b
Warp 0 computing tile 5 of matrix, coords (1, 2), will do 1 loops
Warp 0 loading from idx 256 of a and idx 32 of b


(tensor([[138.,  45.,  47., 115.,  83.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [196.,  90.,  74., 156., 118.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [129.,  66.,  45., 106., 101.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [176

In [9]:
torch.allclose(module.matmul(Qp, Kp.T.contiguous(), False), module.matmul(Qp, Kp, True))

Warp 0 computing tile 0 of matrix, coords (0, 0), will do 1 loops
Warp 0 loading from idx 0 of a and idx 0 of b
Warp 0 computing tile 1 of matrix, coords (0, 1), will do 1 loops
Warp 0 loading from idx 0 of a and idx 16 of b
Warp 0 computing tile 2 of matrix, coords (0, 2), will do 1 loops
Warp 0 loading from idx 0 of a and idx 32 of b
Warp 0 computing tile 3 of matrix, coords (1, 0), will do 1 loops
Warp 0 loading from idx 256 of a and idx 0 of b
Warp 0 computing tile 4 of matrix, coords (1, 1), will do 1 loops
Warp 0 loading from idx 256 of a and idx 16 of b
Warp 0 computing tile 5 of matrix, coords (1, 2), will do 1 loops
Warp 0 loading from idx 256 of a and idx 32 of b
Warp 0 computing tile 0 of matrix, coords (0, 0), will do 1 loops
Warp 0 loading from idx 0 of a and idx 0 of b
Warp 0 computing tile 1 of matrix, coords (0, 1), will do 1 loops
Warp 0 loading from idx 0 of a and idx 16 of b
Warp 0 computing tile 2 of matrix, coords (0, 2), will do 1 loops
Warp 0 loading from idx 0 o

False

In [2]:
# module.matmul(B, Kp, False), module.matmul(B, Kp.T.contiguous(), False)
8192*4

32768